version: '3.4'

services:
  jlserver:
    container_name: jl_server
    build:
      context: .
      dockerfile: JLServer\Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:5000
    ports:
        - "5000:5000"

  jlmigrator:
    container_name: jl_migrator
    build:
      context: .
      dockerfile: JL_Migrator\Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development

  mongodb:
    container_name: jl_mongo
    image: mongo
    ports:
        - "27017:27017"

  sqldb:
    container_name: jl_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: raal
      MYSQL_USER: root
      MYSQL_PASSWORD: raal
      MYSQL_DATABASE: JointLessonDB
    volumes:
        - ./mysql-data:/var/lib/mysql
        - ./mysql-initdb:/docker-entrypoint-initdb.d
    ports:
        - "3306:3306"

  redisdb:
    container_name: jl_redis
    image: redis
    ports:
        - "6379:6379"

volumes:
    database-data:
    mysql-data:
    mysql-initdb: